const optimizedImages = {
  "above-the-nav-left.png": {"avif":[{"src":"/optimized/above-the-nav-left-png-320.avif","width":320},{"src":"/optimized/above-the-nav-left-png-640.avif","width":640},{"src":"/optimized/above-the-nav-left-png-960.avif","width":960},{"src":"/optimized/above-the-nav-left-png-1280.avif","width":1280},{"src":"/optimized/above-the-nav-left-png-1600.avif","width":1600},{"src":"/optimized/above-the-nav-left-png-1920.avif","width":1920},{"src":"/optimized/above-the-nav-left-png-2484.avif","width":2484}],"webp":[{"src":"/optimized/above-the-nav-left-png-320.webp","width":320},{"src":"/optimized/above-the-nav-left-png-640.webp","width":640},{"src":"/optimized/above-the-nav-left-png-960.webp","width":960},{"src":"/optimized/above-the-nav-left-png-1280.webp","width":1280},{"src":"/optimized/above-the-nav-left-png-1600.webp","width":1600},{"src":"/optimized/above-the-nav-left-png-1920.webp","width":1920},{"src":"/optimized/above-the-nav-left-png-2484.webp","width":2484}]},
  "above-the-nav-middle.png": {"avif":[{"src":"/optimized/above-the-nav-middle-png-320.avif","width":320},{"src":"/optimized/above-the-nav-middle-png-640.avif","width":640},{"src":"/optimized/above-the-nav-middle-png-960.avif","width":960},{"src":"/optimized/above-the-nav-middle-png-1280.avif","width":1280},{"src":"/optimized/above-the-nav-middle-png-1600.avif","width":1600},{"src":"/optimized/above-the-nav-middle-png-1920.avif","width":1920},{"src":"/optimized/above-the-nav-middle-png-2171.avif","width":2171}],"webp":[{"src":"/optimized/above-the-nav-middle-png-320.webp","width":320},{"src":"/optimized/above-the-nav-middle-png-640.webp","width":640},{"src":"/optimized/above-the-nav-middle-png-960.webp","width":960},{"src":"/optimized/above-the-nav-middle-png-1280.webp","width":1280},{"src":"/optimized/above-the-nav-middle-png-1600.webp","width":1600},{"src":"/optimized/above-the-nav-middle-png-1920.webp","width":1920},{"src":"/optimized/above-the-nav-middle-png-2171.webp","width":2171}]},
  "above-the-nav-right.png": {"avif":[{"src":"/optimized/above-the-nav-right-png-320.avif","width":320},{"src":"/optimized/above-the-nav-right-png-640.avif","width":640},{"src":"/optimized/above-the-nav-right-png-960.avif","width":960},{"src":"/optimized/above-the-nav-right-png-1280.avif","width":1280},{"src":"/optimized/above-the-nav-right-png-1600.avif","width":1600},{"src":"/optimized/above-the-nav-right-png-1920.avif","width":1920},{"src":"/optimized/above-the-nav-right-png-1943.avif","width":1943}],"webp":[{"src":"/optimized/above-the-nav-right-png-320.webp","width":320},{"src":"/optimized/above-the-nav-right-png-640.webp","width":640},{"src":"/optimized/above-the-nav-right-png-960.webp","width":960},{"src":"/optimized/above-the-nav-right-png-1280.webp","width":1280},{"src":"/optimized/above-the-nav-right-png-1600.webp","width":1600},{"src":"/optimized/above-the-nav-right-png-1920.webp","width":1920},{"src":"/optimized/above-the-nav-right-png-1943.webp","width":1943}]},
  "action-card-back.jpg": {"avif":[{"src":"/optimized/action-card-back-jpg-320.avif","width":320},{"src":"/optimized/action-card-back-jpg-640.avif","width":640},{"src":"/optimized/action-card-back-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/action-card-back-jpg-320.webp","width":320},{"src":"/optimized/action-card-back-jpg-640.webp","width":640},{"src":"/optimized/action-card-back-jpg-892.webp","width":892}]},
  "action-phase-action-card.jpg": {"avif":[{"src":"/optimized/action-phase-action-card-jpg-320.avif","width":320},{"src":"/optimized/action-phase-action-card-jpg-640.avif","width":640},{"src":"/optimized/action-phase-action-card-jpg-960.avif","width":960},{"src":"/optimized/action-phase-action-card-jpg-1280.avif","width":1280},{"src":"/optimized/action-phase-action-card-jpg-1600.avif","width":1600},{"src":"/optimized/action-phase-action-card-jpg-1920.avif","width":1920},{"src":"/optimized/action-phase-action-card-jpg-3158.avif","width":3158}],"webp":[{"src":"/optimized/action-phase-action-card-jpg-320.webp","width":320},{"src":"/optimized/action-phase-action-card-jpg-640.webp","width":640},{"src":"/optimized/action-phase-action-card-jpg-960.webp","width":960},{"src":"/optimized/action-phase-action-card-jpg-1280.webp","width":1280},{"src":"/optimized/action-phase-action-card-jpg-1600.webp","width":1600},{"src":"/optimized/action-phase-action-card-jpg-1920.webp","width":1920},{"src":"/optimized/action-phase-action-card-jpg-3158.webp","width":3158}]},
  "action-phase-purchase.png": {"avif":[{"src":"/optimized/action-phase-purchase-png-320.avif","width":320},{"src":"/optimized/action-phase-purchase-png-640.avif","width":640},{"src":"/optimized/action-phase-purchase-png-960.avif","width":960},{"src":"/optimized/action-phase-purchase-png-1280.avif","width":1280},{"src":"/optimized/action-phase-purchase-png-1600.avif","width":1600},{"src":"/optimized/action-phase-purchase-png-1920.avif","width":1920},{"src":"/optimized/action-phase-purchase-png-5712.avif","width":5712}],"webp":[{"src":"/optimized/action-phase-purchase-png-320.webp","width":320},{"src":"/optimized/action-phase-purchase-png-640.webp","width":640},{"src":"/optimized/action-phase-purchase-png-960.webp","width":960},{"src":"/optimized/action-phase-purchase-png-1280.webp","width":1280},{"src":"/optimized/action-phase-purchase-png-1600.webp","width":1600},{"src":"/optimized/action-phase-purchase-png-1920.webp","width":1920},{"src":"/optimized/action-phase-purchase-png-5712.webp","width":5712}]},
  "bg_website.png": {"avif":[{"src":"/optimized/bg_website-png-320.avif","width":320},{"src":"/optimized/bg_website-png-640.avif","width":640},{"src":"/optimized/bg_website-png-960.avif","width":960},{"src":"/optimized/bg_website-png-1280.avif","width":1280},{"src":"/optimized/bg_website-png-1600.avif","width":1600},{"src":"/optimized/bg_website-png-1920.avif","width":1920},{"src":"/optimized/bg_website-png-3750.avif","width":3750}],"webp":[{"src":"/optimized/bg_website-png-320.webp","width":320},{"src":"/optimized/bg_website-png-640.webp","width":640},{"src":"/optimized/bg_website-png-960.webp","width":960},{"src":"/optimized/bg_website-png-1280.webp","width":1280},{"src":"/optimized/bg_website-png-1600.webp","width":1600},{"src":"/optimized/bg_website-png-1920.webp","width":1920},{"src":"/optimized/bg_website-png-3750.webp","width":3750}]},
  "BREAK PLOT ARMOR.jpg": {"avif":[{"src":"/optimized/BREAK-PLOT-ARMOR-jpg-320.avif","width":320},{"src":"/optimized/BREAK-PLOT-ARMOR-jpg-640.avif","width":640},{"src":"/optimized/BREAK-PLOT-ARMOR-jpg-893.avif","width":893}],"webp":[{"src":"/optimized/BREAK-PLOT-ARMOR-jpg-320.webp","width":320},{"src":"/optimized/BREAK-PLOT-ARMOR-jpg-640.webp","width":640},{"src":"/optimized/BREAK-PLOT-ARMOR-jpg-893.webp","width":893}]},
  "dialog-card.png": {"avif":[{"src":"/optimized/dialog-card-png-320.avif","width":320},{"src":"/optimized/dialog-card-png-640.avif","width":640},{"src":"/optimized/dialog-card-png-960.avif","width":960},{"src":"/optimized/dialog-card-png-1272.avif","width":1272}],"webp":[{"src":"/optimized/dialog-card-png-320.webp","width":320},{"src":"/optimized/dialog-card-png-640.webp","width":640},{"src":"/optimized/dialog-card-png-960.webp","width":960},{"src":"/optimized/dialog-card-png-1272.webp","width":1272}]},
  "dold.png": {"avif":[{"src":"/optimized/dold-png-320.avif","width":320},{"src":"/optimized/dold-png-640.avif","width":640},{"src":"/optimized/dold-png-879.avif","width":879}],"webp":[{"src":"/optimized/dold-png-320.webp","width":320},{"src":"/optimized/dold-png-640.webp","width":640},{"src":"/optimized/dold-png-879.webp","width":879}]},
  "draw-phase-complete.png": {"avif":[{"src":"/optimized/draw-phase-complete-png-320.avif","width":320},{"src":"/optimized/draw-phase-complete-png-640.avif","width":640},{"src":"/optimized/draw-phase-complete-png-960.avif","width":960},{"src":"/optimized/draw-phase-complete-png-1280.avif","width":1280},{"src":"/optimized/draw-phase-complete-png-1600.avif","width":1600},{"src":"/optimized/draw-phase-complete-png-1920.avif","width":1920},{"src":"/optimized/draw-phase-complete-png-5712.avif","width":5712}],"webp":[{"src":"/optimized/draw-phase-complete-png-320.webp","width":320},{"src":"/optimized/draw-phase-complete-png-640.webp","width":640},{"src":"/optimized/draw-phase-complete-png-960.webp","width":960},{"src":"/optimized/draw-phase-complete-png-1280.webp","width":1280},{"src":"/optimized/draw-phase-complete-png-1600.webp","width":1600},{"src":"/optimized/draw-phase-complete-png-1920.webp","width":1920},{"src":"/optimized/draw-phase-complete-png-5712.webp","width":5712}]},
  "draw-phase.png": {"avif":[{"src":"/optimized/draw-phase-png-320.avif","width":320},{"src":"/optimized/draw-phase-png-640.avif","width":640},{"src":"/optimized/draw-phase-png-960.avif","width":960},{"src":"/optimized/draw-phase-png-1280.avif","width":1280},{"src":"/optimized/draw-phase-png-1600.avif","width":1600},{"src":"/optimized/draw-phase-png-1920.avif","width":1920},{"src":"/optimized/draw-phase-png-5712.avif","width":5712}],"webp":[{"src":"/optimized/draw-phase-png-320.webp","width":320},{"src":"/optimized/draw-phase-png-640.webp","width":640},{"src":"/optimized/draw-phase-png-960.webp","width":960},{"src":"/optimized/draw-phase-png-1280.webp","width":1280},{"src":"/optimized/draw-phase-png-1600.webp","width":1600},{"src":"/optimized/draw-phase-png-1920.webp","width":1920},{"src":"/optimized/draw-phase-png-5712.webp","width":5712}]},
  "executioner-card-back.png": {"avif":[{"src":"/optimized/executioner-card-back-png-320.avif","width":320},{"src":"/optimized/executioner-card-back-png-640.avif","width":640},{"src":"/optimized/executioner-card-back-png-703.avif","width":703}],"webp":[{"src":"/optimized/executioner-card-back-png-320.webp","width":320},{"src":"/optimized/executioner-card-back-png-640.webp","width":640},{"src":"/optimized/executioner-card-back-png-703.webp","width":703}]},
  "executioner-dead.png": {"avif":[{"src":"/optimized/executioner-dead-png-320.avif","width":320},{"src":"/optimized/executioner-dead-png-640.avif","width":640},{"src":"/optimized/executioner-dead-png-960.avif","width":960},{"src":"/optimized/executioner-dead-png-1280.avif","width":1280},{"src":"/optimized/executioner-dead-png-1292.avif","width":1292}],"webp":[{"src":"/optimized/executioner-dead-png-320.webp","width":320},{"src":"/optimized/executioner-dead-png-640.webp","width":640},{"src":"/optimized/executioner-dead-png-960.webp","width":960},{"src":"/optimized/executioner-dead-png-1280.webp","width":1280},{"src":"/optimized/executioner-dead-png-1292.webp","width":1292}]},
  "executioner-phase-dead-characters.jpg": {"avif":[{"src":"/optimized/executioner-phase-dead-characters-jpg-320.avif","width":320},{"src":"/optimized/executioner-phase-dead-characters-jpg-640.avif","width":640},{"src":"/optimized/executioner-phase-dead-characters-jpg-960.avif","width":960},{"src":"/optimized/executioner-phase-dead-characters-jpg-1280.avif","width":1280},{"src":"/optimized/executioner-phase-dead-characters-jpg-1600.avif","width":1600},{"src":"/optimized/executioner-phase-dead-characters-jpg-1920.avif","width":1920},{"src":"/optimized/executioner-phase-dead-characters-jpg-5712.avif","width":5712}],"webp":[{"src":"/optimized/executioner-phase-dead-characters-jpg-320.webp","width":320},{"src":"/optimized/executioner-phase-dead-characters-jpg-640.webp","width":640},{"src":"/optimized/executioner-phase-dead-characters-jpg-960.webp","width":960},{"src":"/optimized/executioner-phase-dead-characters-jpg-1280.webp","width":1280},{"src":"/optimized/executioner-phase-dead-characters-jpg-1600.webp","width":1600},{"src":"/optimized/executioner-phase-dead-characters-jpg-1920.webp","width":1920},{"src":"/optimized/executioner-phase-dead-characters-jpg-5712.webp","width":5712}]},
  "executioner-phase-reveal.png": {"avif":[{"src":"/optimized/executioner-phase-reveal-png-320.avif","width":320},{"src":"/optimized/executioner-phase-reveal-png-605.avif","width":605}],"webp":[{"src":"/optimized/executioner-phase-reveal-png-320.webp","width":320},{"src":"/optimized/executioner-phase-reveal-png-605.webp","width":605}]},
  "executioner.jpg": {"avif":[{"src":"/optimized/executioner-jpg-320.avif","width":320},{"src":"/optimized/executioner-jpg-640.avif","width":640},{"src":"/optimized/executioner-jpg-673.avif","width":673}],"webp":[{"src":"/optimized/executioner-jpg-320.webp","width":320},{"src":"/optimized/executioner-jpg-640.webp","width":640},{"src":"/optimized/executioner-jpg-673.webp","width":673}]},
  "GENTLE PUSH.jpg": {"avif":[{"src":"/optimized/GENTLE-PUSH-jpg-320.avif","width":320},{"src":"/optimized/GENTLE-PUSH-jpg-640.avif","width":640},{"src":"/optimized/GENTLE-PUSH-jpg-703.avif","width":703}],"webp":[{"src":"/optimized/GENTLE-PUSH-jpg-320.webp","width":320},{"src":"/optimized/GENTLE-PUSH-jpg-640.webp","width":640},{"src":"/optimized/GENTLE-PUSH-jpg-703.webp","width":703}]},
  "hamlet-dead.png": {"avif":[{"src":"/optimized/hamlet-dead-png-320.avif","width":320},{"src":"/optimized/hamlet-dead-png-640.avif","width":640},{"src":"/optimized/hamlet-dead-png-702.avif","width":702}],"webp":[{"src":"/optimized/hamlet-dead-png-320.webp","width":320},{"src":"/optimized/hamlet-dead-png-640.webp","width":640},{"src":"/optimized/hamlet-dead-png-702.webp","width":702}]},
  "hamlet.jpg": {"avif":[{"src":"/optimized/hamlet-jpg-320.avif","width":320},{"src":"/optimized/hamlet-jpg-640.avif","width":640},{"src":"/optimized/hamlet-jpg-673.avif","width":673}],"webp":[{"src":"/optimized/hamlet-jpg-320.webp","width":320},{"src":"/optimized/hamlet-jpg-640.webp","width":640},{"src":"/optimized/hamlet-jpg-673.webp","width":673}]},
  "impostor.jpg": {"avif":[{"src":"/optimized/impostor-jpg-320.avif","width":320},{"src":"/optimized/impostor-jpg-640.avif","width":640},{"src":"/optimized/impostor-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/impostor-jpg-320.webp","width":320},{"src":"/optimized/impostor-jpg-640.webp","width":640},{"src":"/optimized/impostor-jpg-892.webp","width":892}]},
  "kat.png": {"avif":[{"src":"/optimized/kat-png-320.avif","width":320},{"src":"/optimized/kat-png-640.avif","width":640},{"src":"/optimized/kat-png-877.avif","width":877}],"webp":[{"src":"/optimized/kat-png-320.webp","width":320},{"src":"/optimized/kat-png-640.webp","width":640},{"src":"/optimized/kat-png-877.webp","width":877}]},
  "last-meal.jpg": {"avif":[{"src":"/optimized/last-meal-jpg-320.avif","width":320},{"src":"/optimized/last-meal-jpg-640.avif","width":640},{"src":"/optimized/last-meal-jpg-855.avif","width":855}],"webp":[{"src":"/optimized/last-meal-jpg-320.webp","width":320},{"src":"/optimized/last-meal-jpg-640.webp","width":640},{"src":"/optimized/last-meal-jpg-855.webp","width":855}]},
  "mat.png": {"avif":[{"src":"/optimized/mat-png-320.avif","width":320},{"src":"/optimized/mat-png-586.avif","width":586}],"webp":[{"src":"/optimized/mat-png-320.webp","width":320},{"src":"/optimized/mat-png-586.webp","width":586}]},
  "misero-dead.png": {"avif":[{"src":"/optimized/misero-dead-png-320.avif","width":320},{"src":"/optimized/misero-dead-png-640.avif","width":640},{"src":"/optimized/misero-dead-png-702.avif","width":702}],"webp":[{"src":"/optimized/misero-dead-png-320.webp","width":320},{"src":"/optimized/misero-dead-png-640.webp","width":640},{"src":"/optimized/misero-dead-png-702.webp","width":702}]},
  "misero.png": {"avif":[{"src":"/optimized/misero-png-320.avif","width":320},{"src":"/optimized/misero-png-640.avif","width":640},{"src":"/optimized/misero-png-673.avif","width":673}],"webp":[{"src":"/optimized/misero-png-320.webp","width":320},{"src":"/optimized/misero-png-640.webp","width":640},{"src":"/optimized/misero-png-673.webp","width":673}]},
  "notferatu-dead.png": {"avif":[{"src":"/optimized/notferatu-dead-png-320.avif","width":320},{"src":"/optimized/notferatu-dead-png-640.avif","width":640},{"src":"/optimized/notferatu-dead-png-702.avif","width":702}],"webp":[{"src":"/optimized/notferatu-dead-png-320.webp","width":320},{"src":"/optimized/notferatu-dead-png-640.webp","width":640},{"src":"/optimized/notferatu-dead-png-702.webp","width":702}]},
  "notferatu.jpg": {"avif":[{"src":"/optimized/notferatu-jpg-320.avif","width":320},{"src":"/optimized/notferatu-jpg-640.avif","width":640},{"src":"/optimized/notferatu-jpg-673.avif","width":673}],"webp":[{"src":"/optimized/notferatu-jpg-320.webp","width":320},{"src":"/optimized/notferatu-jpg-640.webp","width":640},{"src":"/optimized/notferatu-jpg-673.webp","width":673}]},
  "paid-guard.jpg": {"avif":[{"src":"/optimized/paid-guard-jpg-320.avif","width":320},{"src":"/optimized/paid-guard-jpg-640.avif","width":640},{"src":"/optimized/paid-guard-jpg-855.avif","width":855}],"webp":[{"src":"/optimized/paid-guard-jpg-320.webp","width":320},{"src":"/optimized/paid-guard-jpg-640.webp","width":640},{"src":"/optimized/paid-guard-jpg-855.webp","width":855}]},
  "papirus texture.jpg": {"avif":[{"src":"/optimized/papirus-texture-jpg-320.avif","width":320},{"src":"/optimized/papirus-texture-jpg-612.avif","width":612}],"webp":[{"src":"/optimized/papirus-texture-jpg-320.webp","width":320},{"src":"/optimized/papirus-texture-jpg-612.webp","width":612}]},
  "paprika-dead.png": {"avif":[{"src":"/optimized/paprika-dead-png-320.avif","width":320},{"src":"/optimized/paprika-dead-png-640.avif","width":640},{"src":"/optimized/paprika-dead-png-702.avif","width":702}],"webp":[{"src":"/optimized/paprika-dead-png-320.webp","width":320},{"src":"/optimized/paprika-dead-png-640.webp","width":640},{"src":"/optimized/paprika-dead-png-702.webp","width":702}]},
  "paprika.jpg": {"avif":[{"src":"/optimized/paprika-jpg-320.avif","width":320},{"src":"/optimized/paprika-jpg-640.avif","width":640},{"src":"/optimized/paprika-jpg-673.avif","width":673}],"webp":[{"src":"/optimized/paprika-jpg-320.webp","width":320},{"src":"/optimized/paprika-jpg-640.webp","width":640},{"src":"/optimized/paprika-jpg-673.webp","width":673}]},
  "plot-armor-all.png": {"avif":[{"src":"/optimized/plot-armor-all-png-320.avif","width":320},{"src":"/optimized/plot-armor-all-png-640.avif","width":640},{"src":"/optimized/plot-armor-all-png-960.avif","width":960},{"src":"/optimized/plot-armor-all-png-1280.avif","width":1280},{"src":"/optimized/plot-armor-all-png-1600.avif","width":1600},{"src":"/optimized/plot-armor-all-png-1719.avif","width":1719}],"webp":[{"src":"/optimized/plot-armor-all-png-320.webp","width":320},{"src":"/optimized/plot-armor-all-png-640.webp","width":640},{"src":"/optimized/plot-armor-all-png-960.webp","width":960},{"src":"/optimized/plot-armor-all-png-1280.webp","width":1280},{"src":"/optimized/plot-armor-all-png-1600.webp","width":1600},{"src":"/optimized/plot-armor-all-png-1719.webp","width":1719}]},
  "resource-card-back.jpg": {"avif":[{"src":"/optimized/resource-card-back-jpg-320.avif","width":320},{"src":"/optimized/resource-card-back-jpg-640.avif","width":640},{"src":"/optimized/resource-card-back-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/resource-card-back-jpg-320.webp","width":320},{"src":"/optimized/resource-card-back-jpg-640.webp","width":640},{"src":"/optimized/resource-card-back-jpg-892.webp","width":892}]},
  "resource-dexterity.jpg": {"avif":[{"src":"/optimized/resource-dexterity-jpg-320.avif","width":320},{"src":"/optimized/resource-dexterity-jpg-640.avif","width":640},{"src":"/optimized/resource-dexterity-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/resource-dexterity-jpg-320.webp","width":320},{"src":"/optimized/resource-dexterity-jpg-640.webp","width":640},{"src":"/optimized/resource-dexterity-jpg-892.webp","width":892}]},
  "resource-holy-duck-tape.jpg": {"avif":[{"src":"/optimized/resource-holy-duck-tape-jpg-320.avif","width":320},{"src":"/optimized/resource-holy-duck-tape-jpg-640.avif","width":640},{"src":"/optimized/resource-holy-duck-tape-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/resource-holy-duck-tape-jpg-320.webp","width":320},{"src":"/optimized/resource-holy-duck-tape-jpg-640.webp","width":640},{"src":"/optimized/resource-holy-duck-tape-jpg-892.webp","width":892}]},
  "resource-intelligence.jpg": {"avif":[{"src":"/optimized/resource-intelligence-jpg-320.avif","width":320},{"src":"/optimized/resource-intelligence-jpg-640.avif","width":640},{"src":"/optimized/resource-intelligence-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/resource-intelligence-jpg-320.webp","width":320},{"src":"/optimized/resource-intelligence-jpg-640.webp","width":640},{"src":"/optimized/resource-intelligence-jpg-892.webp","width":892}]},
  "resource-strength.jpg": {"avif":[{"src":"/optimized/resource-strength-jpg-320.avif","width":320},{"src":"/optimized/resource-strength-jpg-640.avif","width":640},{"src":"/optimized/resource-strength-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/resource-strength-jpg-320.webp","width":320},{"src":"/optimized/resource-strength-jpg-640.webp","width":640},{"src":"/optimized/resource-strength-jpg-892.webp","width":892}]},
  "resource-wisdom.jpg": {"avif":[{"src":"/optimized/resource-wisdom-jpg-320.avif","width":320},{"src":"/optimized/resource-wisdom-jpg-640.avif","width":640},{"src":"/optimized/resource-wisdom-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/resource-wisdom-jpg-320.webp","width":320},{"src":"/optimized/resource-wisdom-jpg-640.webp","width":640},{"src":"/optimized/resource-wisdom-jpg-892.webp","width":892}]},
  "ser.png": {"avif":[{"src":"/optimized/ser-png-320.avif","width":320},{"src":"/optimized/ser-png-640.avif","width":640},{"src":"/optimized/ser-png-960.avif","width":960},{"src":"/optimized/ser-png-1280.avif","width":1280},{"src":"/optimized/ser-png-1600.avif","width":1600},{"src":"/optimized/ser-png-1920.avif","width":1920},{"src":"/optimized/ser-png-2142.avif","width":2142}],"webp":[{"src":"/optimized/ser-png-320.webp","width":320},{"src":"/optimized/ser-png-640.webp","width":640},{"src":"/optimized/ser-png-960.webp","width":960},{"src":"/optimized/ser-png-1280.webp","width":1280},{"src":"/optimized/ser-png-1600.webp","width":1600},{"src":"/optimized/ser-png-1920.webp","width":1920},{"src":"/optimized/ser-png-2142.webp","width":2142}]},
  "setup-board-layout.png": {"avif":[{"src":"/optimized/setup-board-layout-png-320.avif","width":320},{"src":"/optimized/setup-board-layout-png-640.avif","width":640},{"src":"/optimized/setup-board-layout-png-960.avif","width":960},{"src":"/optimized/setup-board-layout-png-1280.avif","width":1280},{"src":"/optimized/setup-board-layout-png-1600.avif","width":1600},{"src":"/optimized/setup-board-layout-png-1920.avif","width":1920},{"src":"/optimized/setup-board-layout-png-10950.avif","width":10950}],"webp":[{"src":"/optimized/setup-board-layout-png-320.webp","width":320},{"src":"/optimized/setup-board-layout-png-640.webp","width":640},{"src":"/optimized/setup-board-layout-png-960.webp","width":960},{"src":"/optimized/setup-board-layout-png-1280.webp","width":1280},{"src":"/optimized/setup-board-layout-png-1600.webp","width":1600},{"src":"/optimized/setup-board-layout-png-1920.webp","width":1920},{"src":"/optimized/setup-board-layout-png-10950.webp","width":10950}]},
  "setup-death-line.png": {"avif":[{"src":"/optimized/setup-death-line-png-320.avif","width":320},{"src":"/optimized/setup-death-line-png-640.avif","width":640},{"src":"/optimized/setup-death-line-png-960.avif","width":960},{"src":"/optimized/setup-death-line-png-1280.avif","width":1280},{"src":"/optimized/setup-death-line-png-1600.avif","width":1600},{"src":"/optimized/setup-death-line-png-1920.avif","width":1920},{"src":"/optimized/setup-death-line-png-10950.avif","width":10950}],"webp":[{"src":"/optimized/setup-death-line-png-320.webp","width":320},{"src":"/optimized/setup-death-line-png-640.webp","width":640},{"src":"/optimized/setup-death-line-png-960.webp","width":960},{"src":"/optimized/setup-death-line-png-1280.webp","width":1280},{"src":"/optimized/setup-death-line-png-1600.webp","width":1600},{"src":"/optimized/setup-death-line-png-1920.webp","width":1920},{"src":"/optimized/setup-death-line-png-10950.webp","width":10950}]},
  "setup-initial-layout.png": {"avif":[{"src":"/optimized/setup-initial-layout-png-320.avif","width":320},{"src":"/optimized/setup-initial-layout-png-640.avif","width":640},{"src":"/optimized/setup-initial-layout-png-960.avif","width":960},{"src":"/optimized/setup-initial-layout-png-1280.avif","width":1280},{"src":"/optimized/setup-initial-layout-png-1600.avif","width":1600},{"src":"/optimized/setup-initial-layout-png-1920.avif","width":1920},{"src":"/optimized/setup-initial-layout-png-10950.avif","width":10950}],"webp":[{"src":"/optimized/setup-initial-layout-png-320.webp","width":320},{"src":"/optimized/setup-initial-layout-png-640.webp","width":640},{"src":"/optimized/setup-initial-layout-png-960.webp","width":960},{"src":"/optimized/setup-initial-layout-png-1280.webp","width":1280},{"src":"/optimized/setup-initial-layout-png-1600.webp","width":1600},{"src":"/optimized/setup-initial-layout-png-1920.webp","width":1920},{"src":"/optimized/setup-initial-layout-png-10950.webp","width":10950}]},
  "switch.jpg": {"avif":[{"src":"/optimized/switch-jpg-320.avif","width":320},{"src":"/optimized/switch-jpg-640.avif","width":640},{"src":"/optimized/switch-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/switch-jpg-320.webp","width":320},{"src":"/optimized/switch-jpg-640.webp","width":640},{"src":"/optimized/switch-jpg-892.webp","width":892}]},
  "THE IMPOSTOREST.jpg": {"avif":[{"src":"/optimized/THE-IMPOSTOREST-jpg-320.avif","width":320},{"src":"/optimized/THE-IMPOSTOREST-jpg-640.avif","width":640},{"src":"/optimized/THE-IMPOSTOREST-jpg-893.avif","width":893}],"webp":[{"src":"/optimized/THE-IMPOSTOREST-jpg-320.webp","width":320},{"src":"/optimized/THE-IMPOSTOREST-jpg-640.webp","width":640},{"src":"/optimized/THE-IMPOSTOREST-jpg-893.webp","width":893}]},
  "unfair-trade.jpg": {"avif":[{"src":"/optimized/unfair-trade-jpg-320.avif","width":320},{"src":"/optimized/unfair-trade-jpg-640.avif","width":640},{"src":"/optimized/unfair-trade-jpg-892.avif","width":892}],"webp":[{"src":"/optimized/unfair-trade-jpg-320.webp","width":320},{"src":"/optimized/unfair-trade-jpg-640.webp","width":640},{"src":"/optimized/unfair-trade-jpg-892.webp","width":892}]},
  "you-are-up-next.jpg": {"avif":[{"src":"/optimized/you-are-up-next-jpg-320.avif","width":320},{"src":"/optimized/you-are-up-next-jpg-640.avif","width":640},{"src":"/optimized/you-are-up-next-jpg-869.avif","width":869}],"webp":[{"src":"/optimized/you-are-up-next-jpg-320.webp","width":320},{"src":"/optimized/you-are-up-next-jpg-640.webp","width":640},{"src":"/optimized/you-are-up-next-jpg-869.webp","width":869}]},
};

const sortedAssetNames = Object.keys(optimizedImages).sort(
  (left, right) => right.length - left.length,
);

export function getOptimizedImageSources(src) {
  if (!src) return null;

  const fileName = decodeURIComponent(
    String(src).split(/[?#]/, 1)[0].split("/").pop() || "",
  );
  const exactSources = optimizedImages[fileName];

  if (exactSources) return exactSources;

  const matchingAssetName = sortedAssetNames.find((assetName) => {
    const extension = pathExtension(assetName);
    const stem = assetName.slice(0, -extension.length);
    return fileName.startsWith(stem + "-") && fileName.endsWith(extension);
  });

  return matchingAssetName ? optimizedImages[matchingAssetName] : null;
}

function pathExtension(fileName) {
  return fileName.slice(fileName.lastIndexOf("."));
}

export default optimizedImages;
